# .goreleaser.yml
# Build customization
builds:
  - binary: spleen-server
    main: ./server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format_overrides:
      - goos: windows
        format: zip
  files:
    - .server.json
